export const EXAM_CONFIG = {
  PASS_SCORE: 60,
  DEFAULT_TIME_LIMIT: 60,
  WARNING_TIME_5MIN: 300,
  WARNING_TIME_1MIN: 60,
  BEEP_FREQ_NEAR: 880,
  BEEP_FREQ_FAR: 660
}

export const SCORE_LEVELS = {
  EXCELLENT: 90,
  GOOD: 80,
  FAIR: 70,
  PASS: 60
}
